ShopOnline/Areas/Admin/Controllers/ProductCategoryController.cs
using DB.DAO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShopOnline.Areas.Admin.Models;
using ShopOnline.Common;
using DB.EF;

namespace ShopOnline.Areas.Admin.Controllers
{
    public class ProductCategoryController : Controller
    {
        // GET: Admin/Product


        #region --- Product category ----
        public ActionResult Index(string keySearch = "")
        {
            //lay du lieu tu DB->Dao->ProductCategoryDao
            ProductCategoryDao pcDao = new ProductCategoryDao();
            //lay tat ca
            var listPC = pcDao.GetAllProductCategories(keySearch);
            //chua co du lieu
            var model = new List<ProductCategoryModel>();

            foreach (var i in listPC)
            {
                var item = new ProductCategoryModel();
                item.Id = i.ID;
                item.Name = i.Name;
                item.CreatedBy = i.CreatedBy;
                item.CreatedDate = i.CreatedDate.HasValue ? i.CreatedDate.Value.ToShortDateString() : "";
                item.ModifiedDate = i.ModifiedDate.HasValue ? i.ModifiedDate.Value.ToShortDateString() : "";
                item.Status = i.Status;
                item.ModifiedBy = i.ModifiedBy;
                item.ImagePath = i.ImagePath;

                model.Add(item);
            }

            return View(model);
        }

        public ActionResult EditCategory(int id)
        {
            ProductCategoryDao pCDao = new ProductCategoryDao();
            var productCategory = pCDao.GetProductCategoryById(id);
            if (productCategory != null)
            {
                var model = new ProductCategoryModel();

                model.Id = productCategory.ID;
                model.Name = productCategory.Name;
                model.Status = productCategory.Status;
                model.ImagePath = productCategory.ImagePath;

                return View(model);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        //sua danh muc san pham
        [HttpPost]
        public ActionResult EditCategory(ProductCategoryModel model, HttpPostedFileBase file)
        {
            if (model.Id != 0)
            {
                ProductCategoryDao pcDao = new ProductCategoryDao();
                var productCategory = pcDao.GetProductCategoryById(model.Id);
                productCategory.Name = model.Name;
                productCategory.Status = model.Status;
                productCategory.ModifiedDate = DateTime.Now;
                productCategory.ModifiedBy = Constants.Admin;

                if (file != null)
                {
                    string fileName = System.IO.Path.GetFileName(file.FileName);
                    var filePath = "/Content/Images/" + fileName;
                    string path = System.IO.Path.Combine(Server.MapPath("~/Content/Images"), fileName);
                    file.SaveAs(path);
                    model.ImagePath = filePath;
                    productCategory.ImagePath = model.ImagePath;
                }

                pcDao.UpdateProductCategory(productCategory);
            }

            return RedirectToAction("Index");
        }

        public ActionResult AddCategory()
        {
            var model = new ProductCategoryModel();
            model.Status = true;
            return View(model);
        }

        //them danh muc san pham
        [HttpPost]
        public ActionResult AddCategory(ProductCategoryModel model, HttpPostedFileBase file)
        {
            var productCategory = new ProductCategory();
            productCategory.Name = model.Name;
            productCategory.Status = model.Status;
            productCategory.CreatedDate = DateTime.Now;
            productCategory.CreatedBy = Constants.Admin;

            if (file != null)
            {
                string fileName = System.IO.Path.GetFileName(file.FileName);
                var filePath = "/Content/Images/" + fileName;
                string path = System.IO.Path.Combine(Server.MapPath("~/Content/Images"), fileName);
                file.SaveAs(path);
                model.ImagePath = filePath;
                productCategory.ImagePath = model.ImagePath;
            }

            ProductCategoryDao pcDao = new ProductCategoryDao();
            pcDao.UpdateProductCategory(productCategory);

            return RedirectToAction("Index");
        }

        #endregion


    }
}

ShopOnline/Controllers/ContactController.cs
using DB.DAO;
using DB.EF;
using ShopOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopOnline.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(ContactModel model)
        {
            if(ModelState.IsValid)
            {
                ContactDao contactDao = new ContactDao();
                Feedback fb = new Feedback();

                //chuyen doi data from model to feedback 
                fb.Name = model.FullName;
                fb.Phone = model.PhoneNumber;
                fb.Email = model.Email;
                fb.Content = model.Content;
                fb.Address = model.Address;
                fb.Status = true;
                fb.CreatedDate = DateTime.Now;
                
                contactDao.Insert(fb);
                ViewBag.SuccessMessage = "Your submission is successfully";
            }

            return View();
        }
    }
}

ShopOnline/Controllers/LoginController.cs
using DB.DAO;
using ShopOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopOnline.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult Index(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var userDao = new UserDao();
                if (userDao.Login(model.UserName, model.Password))
                {
                    return RedirectToAction("Index", "Home", new { area = "Admin" });
                }
                else
                {
                    model.UserName = string.Empty;
                    model.Password = string.Empty;
                    ViewBag.errorMessage = "Account not exist.";
                    return View(model);
                }
            }

            return View(model);
        }
    }
}

ShopOnline/Controllers/ProductController.cs
using DB.DAO;
using DB.EF;
using ShopOnline.Models;
using ShopOnline.Models.Products;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopOnline.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult _ProductItem(ProductItemModel model)
        {
            return PartialView(model);
        }

        public ActionResult Detail(int productId)
        {
            ProductDao productDao = new ProductDao();

            var product = productDao.GetProductById(productId);

            // chuyen doi dl tu db sang model de hien thi
            var model = new ProductItemModel();
            model.Id = product.ID;
            model.Title = product.Name;
            model.Price = product.Price ?? 0;//co the co gia tr hoac khong ? neu co gia tri thi hien gt ? nguoc lai hien thi 0
            model.ImageURL = product.Image;
            model.Description = product.Descriptions;

            return View(model);
        }

        public ActionResult ProductCategory(int productCategoryId)
        {
            var productCategoryDao = new ProductCategoryDao();
            var productDao = new ProductDao();

            var category = productCategoryDao.GetProductCategoryById(productCategoryId);
            var listProducts = productDao.GetProductsByCategory(productCategoryId);

            var model = new ProductCategories();
            model = converToProductCategories(listProducts, category);

            return View(model);
        }

        #region--Private----
        private ProductCategoryModel convertCategoryToCategoryModel(ProductCategory productCategory)
        {
            var model = new ProductCategoryModel();
            model.Id = productCategory.ID;
            model.Name = productCategory.Name;
            model.ImageURL = productCategory.ImagePath;

            return model;
        }

        private ProductItemModel convertProductToProductItemModel(Product product)
        {
            var model = new ProductItemModel();
            model.Id = product.ID;
            model.ImageURL = product.Image;
            model.Price = product.Price.Value;
            model.Title = product.Name;

            return model;
        }

        private List<ProductItemModel> convertProductsToListProductModel(List<Product> products)
        {
            var model = new List<ProductItemModel>();
            foreach (var item in products)
            {
                var productItem = convertProductToProductItemModel(item);

                model.Add(productItem);
            }

            return model;
        }

        private ProductCategories converToProductCategories(List<Product> products, ProductCategory productCategory)
        {
            var model = new ProductCategories();
            model.Category = convertCategoryToCategoryModel(productCategory);
            if (products.Count > 0)
            {
                model.Products = convertProductsToListProductModel(products);
            }

            return model;
        }
        #endregion
    }
}

ShopOnline/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Admin</title>
    <!-- Bootstrap Core CSS -->
    <link href="~/Content/SBAdmin/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <!-- MetisMenu CSS -->
    <link href="~/Content/SBAdmin/vendor/metisMenu/metisMenu.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="~/Content/SBAdmin/dist/css/sb-admin-2.css" rel="stylesheet">
    <!-- Morris Charts CSS -->
    <link href="~/Content/SBAdmin/vendor/morrisjs/morris.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="~/Content/SBAdmin/vendor/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <link rel="stylesheet" type="text/css" href="~/Content/style.css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <!-- /.navbar-header -->
            <ul class="nav navbar-top-links navbar-right">
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li>
                            <a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="login.html"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
            </ul>
            <!-- /.navbar-top-links -->
            <div class="navbar-default sidebar" role="navigation">
                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <a href="@Url.Action("Index","Product",new { area="admin"})"><i class="fa fa-calendar-times-o fa-fw"></i> Quản lí sản phẩm</a>
                        </li>
                        <li>
                            <a href="tables.html"><i class="fa fa-user fa-fw"></i> Quản lí người dùng</a>
                        </li>
                        <li>
                            <a href="tables.html"><i class="fa fa-contao fa-fw"></i> Quản lí liên hệ</a>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","ProductCategory",new { area="admin"})"><i class="fa fa-product-hunt fa-fw"></i> Quản lí danh mục sản phẩm</a>
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>
        <div id="page-wrapper">
            @RenderBody()
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    <!-- jQuery -->
    <script src="~/Content/SBAdmin/vendor/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Content/SBAdmin/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/Content/SBAdmin/vendor/metisMenu/metisMenu.min.js"></script>
    <!-- Morris Charts JavaScript -->
    <script src="~/Content/SBAdmin/vendor/raphael/raphael.min.js"></script>
    <script src="~/Content/SBAdmin/vendor/morrisjs/morris.min.js"></script>
    <script src="~/Content/SBAdmin/data/morris-data.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="~/Content/SBAdmin/dist/js/sb-admin-2.js"></script>
</body>
</html>

ShopOnline/Areas/Admin/Views/Shared/_header.cshtml
@using DB.DAO;
@{ 
    ProductDao productDao = new ProductDao();
    ProductCategoryDao productCategoryDao = new ProductCategoryDao();

    var listCategories = productCategoryDao.GetAllActiveProductCategories();
}

<header class="header1">
    <!-- Header desktop -->
    <div class="container-menu-header">
        <div class="topbar">
            <div class="topbar-social">
                <a href="#" class="topbar-social-item fa fa-facebook"></a>
                <a href="#" class="topbar-social-item fa fa-instagram"></a>
                <a href="#" class="topbar-social-item fa fa-pinterest-p"></a>
                <a href="#" class="topbar-social-item fa fa-snapchat-ghost"></a>
                <a href="#" class="topbar-social-item fa fa-youtube-play"></a>
            </div>

            <span class="topbar-child1">
                Free shipping for standard order over $100
            </span>

            <div class="topbar-child2">
                <span class="topbar-email">
                    huyennguyen.up@gmail.com
                </span>
            </div>
        </div>

        <div class="wrap_header">
            <!-- Logo -->
            <a href="index.html" class="logo">
                <img src="~/Content/Images/logo.jpg" alt="IMG-LOGO">
            </a>

            <!-- Menu -->
            <div class="wrap_menu">
                <nav class="menu">
                    <ul class="main_menu">
                        <li>
                            <a href="@Url.Action("Index","Home")">Home</a>
                        </li>

                        <li>
                            <a href="product.html">About</a>
                        </li>

                        <li class="sale-noti">
                            <a href="product.html">Product</a>
                            <ul class="sub_menu">
                                @foreach (var item in listCategories)
                                {
                                    <li><a href="@Url.Action("ProductCategory", "Product", new {productCategoryId = item.ID })">@item.Name</a></li>
                                }
                            </ul>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Contact")">Contact</a>
                        </li>
                    </ul>
                </nav>
            </div>

            <!-- Header Icon -->
            <div class="header-icons">
                <a href="@Url.Action("Index","Login")" class="header-wrapicon1 dis-block">
                    <img src="~/Content/Theme/images/icons/icon-header-01.png" class="header-icon1" alt="ICON">
                </a>

                <span class="linedivide1"></span>

                <div class="header-wrapicon2">
                    <img src="~/Content/Theme/images/icons/icon-header-02.png" class="header-icon1 js-show-header-dropdown" alt="ICON">
                    <span class="header-icons-noti">0</span>

                    <!-- Header cart noti -->
                    <div class="header-cart header-dropdown">
                        <ul class="header-cart-wrapitem">
                            <li class="header-cart-item">
                                <div class="header-cart-item-img">
                                    <img src="images/item-cart-01.jpg" alt="IMG">
                                </div>

                                <div class="header-cart-item-txt">
                                    <a href="#" class="header-cart-item-name">
                                        White Shirt With Pleat Detail Back
                                    </a>

                                    <span class="header-cart-item-info">
                                        1 x $19.00
                                    </span>
                                </div>
                            </li>

                            <li class="header-cart-item">
                                <div class="header-cart-item-img">
                                    <img src="images/item-cart-02.jpg" alt="IMG">
                                </div>

                                <div class="header-cart-item-txt">
                                    <a href="#" class="header-cart-item-name">
                                        Converse All Star Hi Black Canvas
                                    </a>

                                    <span class="header-cart-item-info">
                                        1 x $39.00
                                    </span>
                                </div>
                            </li>

                            <li class="header-cart-item">
                                <div class="header-cart-item-img">
                                    <img src="images/item-cart-03.jpg" alt="IMG">
                                </div>

                                <div class="header-cart-item-txt">
                                    <a href="#" class="header-cart-item-name">
                                        Nixon Porter Leather Watch In Tan
                                    </a>

                                    <span class="header-cart-item-info">
                                        1 x $17.00
                                    </span>
                                </div>
                            </li>
                        </ul>

                        <div class="header-cart-total">
                            Total: $75.00
                        </div>

                        <div class="header-cart-buttons">
                            <div class="header-cart-wrapbtn">
                                <!-- Button -->
                                <a href="cart.html" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
                                    View Cart
                                </a>
                            </div>

                            <div class="header-cart-wrapbtn">
                                <!-- Button -->
                                <a href="#" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
                                    Check Out
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Header Mobile -->
    <div class="wrap_header_mobile">
        <!-- Logo moblie -->
        <a href="index.html" class="logo-mobile">
            <img src="images/icons/logo.png" alt="IMG-LOGO">
        </a>

        <!-- Button show menu -->
        <div class="btn-show-menu">
            <!-- Header Icon mobile -->
            <div class="header-icons-mobile">
                <a href="#" class="header-wrapicon1 dis-block">
                    <img src="images/icons/icon-header-01.png" class="header-icon1" alt="ICON">
                </a>

                <span class="linedivide2"></span>

                <div class="header-wrapicon2">
                    <img src="images/icons/icon-header-02.png" class="header-icon1 js-show-header-dropdown" alt="ICON">
                    <span class="header-icons-noti">0</span>

                    <!-- Header cart noti -->
                    <div class="header-cart header-dropdown">
                        <ul class="header-cart-wrapitem">
                            <li class="header-cart-item">
                                <div class="header-cart-item-img">
                                    <img src="images/item-cart-01.jpg" alt="IMG">
                                </div>

                                <div class="header-cart-item-txt">
                                    <a href="#" class="header-cart-item-name">
                                        White Shirt With Pleat Detail Back
                                    </a>

                                    <span class="header-cart-item-info">
                                        1 x $19.00
                                    </span>
                                </div>
                            </li>

                            <li class="header-cart-item">
                                <div class="header-cart-item-img">
                                    <img src="images/item-cart-02.jpg" alt="IMG">
                                </div>

                                <div class="header-cart-item-txt">
                                    <a href="#" class="header-cart-item-name">
                                        Converse All Star Hi Black Canvas
                                    </a>

                                    <span class="header-cart-item-info">
                                        1 x $39.00
                                    </span>
                                </div>
                            </li>

                            <li class="header-cart-item">
                                <div class="header-cart-item-img">
                                    <img src="images/item-cart-03.jpg" alt="IMG">
                                </div>

                                <div class="header-cart-item-txt">
                                    <a href="#" class="header-cart-item-name">
                                        Nixon Porter Leather Watch In Tan
                                    </a>

                                    <span class="header-cart-item-info">
                                        1 x $17.00
                                    </span>
                                </div>
                            </li>
                        </ul>

                        <div class="header-cart-total">
                            Total: $75.00
                        </div>

                        <div class="header-cart-buttons">
                            <div class="header-cart-wrapbtn">
                                <!-- Button -->
                                <a href="cart.html" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
                                    View Cart
                                </a>
                            </div>

                            <div class="header-cart-wrapbtn">
                                <!-- Button -->
                                <a href="#" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
                                    Check Out
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="btn-show-menu-mobile hamburger hamburger--squeeze">
                <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                </span>
            </div>
        </div>
    </div>

    <!-- Menu Mobile -->
    <div class="wrap-side-menu">
        <nav class="side-menu">
            <ul class="main-menu">
                <li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
                    <span class="topbar-child1">
                        Free shipping for standard order over $100
                    </span>
                </li>

                <li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
                    <div class="topbar-child2-mobile">
                        <span class="topbar-email">
                            fashe@example.com
                        </span>

                        <div class="topbar-language rs1-select2">
                            <select class="selection-1" name="time">
                                <option>USD</option>
                                <option>EUR</option>
                            </select>
                        </div>
                    </div>
                </li>

                <li class="item-topbar-mobile p-l-10">
                    <div class="topbar-social-mobile">
                        <a href="#" class="topbar-social-item fa fa-facebook"></a>
                        <a href="#" class="topbar-social-item fa fa-instagram"></a>
                        <a href="#" class="topbar-social-item fa fa-pinterest-p"></a>
                        <a href="#" class="topbar-social-item fa fa-snapchat-ghost"></a>
                        <a href="#" class="topbar-social-item fa fa-youtube-play"></a>
                    </div>
                </li>

                <li class="item-menu-mobile">
                    <a href="index.html">Home</a>
                    <ul class="sub-menu">
                        <li><a href="index.html">Homepage V1</a></li>
                        <li><a href="home-02.html">Homepage V2</a></li>
                        <li><a href="home-03.html">Homepage V3</a></li>
                    </ul>
                    <i class="arrow-main-menu fa fa-angle-right" aria-hidden="true"></i>
                </li>

                <li class="item-menu-mobile">
                    <a href="product.html">Shop</a>
                </li>

                <li class="item-menu-mobile">
                    <a href="product.html">Sale</a>
                </li>

                <li class="item-menu-mobile">
                    <a href="cart.html">Features</a>
                </li>

                <li class="item-menu-mobile">
                    <a href="about.html">About</a>
                </li>

                <li class="item-menu-mobile">
                    <a href="contact.html">Contact</a>
                </li>
            </ul>
        </nav>
    </div>
</header>