ShopOnline/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopOnline.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }
    }
}

ShopOnline/Controllers/ContactController.cs
using DB.DAO;
using DB.EF;
using ShopOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopOnline.Controllers
{
    public class ContactController : Controller
    {
        // GET: Contact
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(ContactModel model)
        {
            if(ModelState.IsValid)
            {
                ContactDao contactDao = new ContactDao();
                Feedback fb = new Feedback();

                //chuyen doi data from model to feedback 
                fb.Name = model.FullName;
                fb.Phone = model.PhoneNumber;
                fb.Email = model.Email;
                fb.Content = model.Content;
                fb.Address = model.Address;
                fb.Status = true;
                fb.CreatedDate = DateTime.Now;
                
                contactDao.Insert(fb);
                ViewBag.SuccessMessage = "Your submission is successfully";
            }

            return View();
        }
    }
}

ShopOnline/Controllers/LoginController.cs
using DB.DAO;
using ShopOnline.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopOnline.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult Index(LoginModel model)
        {
            if (ModelState.IsValid)
            {
                var userDao = new UserDao();
                if (userDao.Login(model.UserName, model.Password))
                {
                    return RedirectToAction("Index", "Home", new { area = "Admin" });
                }
                else
                {
                    model.UserName = string.Empty;
                    model.Password = string.Empty;
                    ViewBag.errorMessage = "Account not exist.";
                    return View(model);
                }
            }

            return View(model);
        }
    }
}

ShopOnline/Controllers/ProductController.cs
using DB.DAO;
using DB.EF;
using ShopOnline.Models;
using ShopOnline.Models.Products;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopOnline.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult _ProductItem(ProductItemModel model)
        {
            return PartialView(model);
        }

        public ActionResult Detail(int productId)
        {
            ProductDao productDao = new ProductDao();

            var product = productDao.GetProductById(productId);

            // chuyen doi dl tu db sang model de hien thi
            var model = new ProductItemModel();
            model.Id = product.ID;
            model.Title = product.Name;
            model.Price = product.Price ?? 0;//co the co gia tr hoac khong ? neu co gia tri thi hien gt ? nguoc lai hien thi 0
            model.ImageURL = product.Image;
            model.Description = product.Descriptions;

            return View(model);
        }

        public ActionResult ProductCategory(int productCategoryId)
        {
            var productCategoryDao = new ProductCategoryDao();
            var productDao = new ProductDao();

            var category = productCategoryDao.GetProductCategoryById(productCategoryId);
            var listProducts = productDao.GetProductsByCategory(productCategoryId);

            var model = new ProductCategories();
            model = converToProductCategories(listProducts, category);

            return View(model);
        }

        #region--Private----
        private ProductCategoryModel convertCategoryToCategoryModel(ProductCategory productCategory)
        {
            var model = new ProductCategoryModel();
            model.Id = productCategory.ID;
            model.Name = productCategory.Name;
            model.ImageURL = productCategory.ImagePath;

            return model;
        }

        private ProductItemModel convertProductToProductItemModel(Product product)
        {
            var model = new ProductItemModel();
            model.Id = product.ID;
            model.ImageURL = product.Image;
            model.Price = product.Price.Value;
            model.Title = product.Name;

            return model;
        }

        private List<ProductItemModel> convertProductsToListProductModel(List<Product> products)
        {
            var model = new List<ProductItemModel>();
            foreach (var item in products)
            {
                var productItem = convertProductToProductItemModel(item);

                model.Add(productItem);
            }

            return model;
        }

        private ProductCategories converToProductCategories(List<Product> products, ProductCategory productCategory)
        {
            var model = new ProductCategories();
            model.Category = convertCategoryToCategoryModel(productCategory);
            if (products.Count > 0)
            {
                model.Products = convertProductsToListProductModel(products);
            }

            return model;
        }
        #endregion
    }
}

ShopOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Home</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="images/icons/favicon.png" />
    <!--===============================================================================================-->
    
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/Theme/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/Theme/fonts/themify/themify-icons.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/Theme/fonts/Linearicons-Free-v1.0.0/icon-font.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/Theme/fonts/elegant-font/html-css/style.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/Theme/vendor/animate/animate.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/Theme/vendor/css-hamburgers/hamburgers.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/Theme/vendor/animsition/css/animsition.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/Theme/vendor/select2/select2.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/Theme/vendor/daterangepicker/daterangepicker.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/Theme/vendor/slick/slick.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/Theme/vendor/lightbox2/css/lightbox.min.css">
    <!--===============================================================================================-->
    <link rel="stylesheet" type="text/css" href="~/Content/Theme/css/util.css">
    <link rel="stylesheet" type="text/css" href="~/Content/Theme/css/main.css">
    <link rel="stylesheet" type="text/css" href="~/Content/style.css">
    <link rel="stylesheet" type="text/css" href="~/Content/Theme/vendor/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/bootstrap.min.css">
    <!--===============================================================================================-->
    <script type="text/javascript" src="~/Content/Theme/vendor/jquery/jquery-3.2.1.min.js"></script>
    <!--===============================================================================================-->
</head>
<body class="animsition">

    <!-- Header -->
    @Html.Partial("_header")

    <!-- Body -->
    @RenderBody()

    <!-- Footer -->
   @Html.Partial("_footer")

    <!-- Back to top -->
    <div class="btn-back-to-top bg0-hov" id="myBtn">
        <span class="symbol-btn-back-to-top">
            <i class="fa fa-angle-double-up" aria-hidden="true"></i>
        </span>
    </div>

    <!-- Container Selection1 -->
    <div id="dropDownSelect1"></div>

    <!--===============================================================================================-->
    <script type="text/javascript" src="~/Content/Theme/vendor/animsition/js/animsition.min.js"></script>
    <!--===============================================================================================-->
    <script type="text/javascript" src="~/Content/Theme/vendor/bootstrap/js/popper.js"></script>
    <script type="text/javascript" src="~/Content/Theme/vendor/bootstrap/js/bootstrap.min.js"></script>
    <!--===============================================================================================-->
    <script type="text/javascript" src="~/Content/Theme/vendor/select2/select2.min.js"></script>
    <script type="text/javascript">
		$(".selection-1").select2({
			minimumResultsForSearch: 20,
			dropdownParent: $('#dropDownSelect1')
		});
    </script>
    <!--===============================================================================================-->
    <script type="text/javascript" src="~/Content/Theme/vendor/slick/slick.min.js"></script>
    <script type="text/javascript" src="~/Content/Theme/js/slick-custom.js"></script>
    <!--===============================================================================================-->
    <script type="text/javascript" src="~/Content/Theme/vendor/countdowntime/countdowntime.js"></script>
    <!--===============================================================================================-->
    <script type="text/javascript" src="~/Content/Theme/vendor/lightbox2/js/lightbox.min.js"></script>
    <!--===============================================================================================-->
    <script type="text/javascript" src="~/Content/Theme/vendor/sweetalert/sweetalert.min.js"></script>
    <script type="text/javascript">
		$('.block2-btn-addcart').each(function(){
			var nameProduct = $(this).parent().parent().parent().find('.block2-name').html();
			$(this).on('click', function(){
				swal(nameProduct, "is added to cart !", "success");
			});
		});

		$('.block2-btn-addwishlist').each(function(){
			var nameProduct = $(this).parent().parent().parent().find('.block2-name').html();
			$(this).on('click', function(){
				swal(nameProduct, "is added to wishlist !", "success");
			});
		});
    </script>

    <!--===============================================================================================-->
    <script src="~/Content/Theme/js/main.js"></script>

</body>
</html>

ShopOnline/Views/Shared/_header.cshtml
@using DB.DAO;
@{ 
    ProductDao productDao = new ProductDao();
    ProductCategoryDao productCategoryDao = new ProductCategoryDao();

    var listCategories = productCategoryDao.GetAllActiveProductCategories();
}

<header class="header1">
    <!-- Header desktop -->
    <div class="container-menu-header">
        <div class="topbar">
            <div class="topbar-social">
                <a href="#" class="topbar-social-item fa fa-facebook"></a>
                <a href="#" class="topbar-social-item fa fa-instagram"></a>
                <a href="#" class="topbar-social-item fa fa-pinterest-p"></a>
                <a href="#" class="topbar-social-item fa fa-snapchat-ghost"></a>
                <a href="#" class="topbar-social-item fa fa-youtube-play"></a>
            </div>

            <span class="topbar-child1">
                Free shipping for standard order over $100
            </span>

            <div class="topbar-child2">
                <span class="topbar-email">
                    huyennguyen.up@gmail.com
                </span>
            </div>
        </div>

        <div class="wrap_header">
            <!-- Logo -->
            <a href="index.html" class="logo">
                <img src="~/Content/Images/logo.jpg" alt="IMG-LOGO">
            </a>

            <!-- Menu -->
            <div class="wrap_menu">
                <nav class="menu">
                    <ul class="main_menu">
                        <li>
                            <a href="@Url.Action("Index","Home")">Home</a>
                        </li>

                        <li>
                            <a href="@Url.Action("Index","About")">About</a>
                        </li>

                        <li class="sale-noti">
                            <a href="product.html">Product</a>
                            <ul class="sub_menu">
                                @foreach (var item in listCategories)
                                {
                                    <li><a href="@Url.Action("ProductCategory", "Product", new {productCategoryId = item.ID })">@item.Name</a></li>
                                }
                            </ul>
                        </li>
                        <li>
                            <a href="@Url.Action("Index","Contact")">Contact</a>
                        </li>
                    </ul>
                </nav>
            </div>

            <!-- Header Icon -->
            <div class="header-icons">
                <a href="@Url.Action("Index","Login")" class="header-wrapicon1 dis-block">
                    <img src="~/Content/Theme/images/icons/icon-header-01.png" class="header-icon1" alt="ICON">
                </a>

                <span class="linedivide1"></span>

                <div class="header-wrapicon2">
                    <img src="~/Content/Theme/images/icons/icon-header-02.png" class="header-icon1 js-show-header-dropdown" alt="ICON">
                    <span class="header-icons-noti">0</span>

                    <!-- Header cart noti -->
                    <div class="header-cart header-dropdown">
                        <ul class="header-cart-wrapitem">
                            <li class="header-cart-item">
                                <div class="header-cart-item-img">
                                    <img src="images/item-cart-01.jpg" alt="IMG">
                                </div>

                                <div class="header-cart-item-txt">
                                    <a href="#" class="header-cart-item-name">
                                        White Shirt With Pleat Detail Back
                                    </a>

                                    <span class="header-cart-item-info">
                                        1 x $19.00
                                    </span>
                                </div>
                            </li>

                            <li class="header-cart-item">
                                <div class="header-cart-item-img">
                                    <img src="images/item-cart-02.jpg" alt="IMG">
                                </div>

                                <div class="header-cart-item-txt">
                                    <a href="#" class="header-cart-item-name">
                                        Converse All Star Hi Black Canvas
                                    </a>

                                    <span class="header-cart-item-info">
                                        1 x $39.00
                                    </span>
                                </div>
                            </li>

                            <li class="header-cart-item">
                                <div class="header-cart-item-img">
                                    <img src="images/item-cart-03.jpg" alt="IMG">
                                </div>

                                <div class="header-cart-item-txt">
                                    <a href="#" class="header-cart-item-name">
                                        Nixon Porter Leather Watch In Tan
                                    </a>

                                    <span class="header-cart-item-info">
                                        1 x $17.00
                                    </span>
                                </div>
                            </li>
                        </ul>

                        <div class="header-cart-total">
                            Total: $75.00
                        </div>

                        <div class="header-cart-buttons">
                            <div class="header-cart-wrapbtn">
                                <!-- Button -->
                                <a href="cart.html" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
                                    View Cart
                                </a>
                            </div>

                            <div class="header-cart-wrapbtn">
                                <!-- Button -->
                                <a href="#" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
                                    Check Out
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Header Mobile -->
    <div class="wrap_header_mobile">
        <!-- Logo moblie -->
        <a href="index.html" class="logo-mobile">
            <img src="images/icons/logo.png" alt="IMG-LOGO">
        </a>

        <!-- Button show menu -->
        <div class="btn-show-menu">
            <!-- Header Icon mobile -->
            <div class="header-icons-mobile">
                <a href="#" class="header-wrapicon1 dis-block">
                    <img src="images/icons/icon-header-01.png" class="header-icon1" alt="ICON">
                </a>

                <span class="linedivide2"></span>

                <div class="header-wrapicon2">
                    <img src="images/icons/icon-header-02.png" class="header-icon1 js-show-header-dropdown" alt="ICON">
                    <span class="header-icons-noti">0</span>

                    <!-- Header cart noti -->
                    <div class="header-cart header-dropdown">
                        <ul class="header-cart-wrapitem">
                            <li class="header-cart-item">
                                <div class="header-cart-item-img">
                                    <img src="images/item-cart-01.jpg" alt="IMG">
                                </div>

                                <div class="header-cart-item-txt">
                                    <a href="#" class="header-cart-item-name">
                                        White Shirt With Pleat Detail Back
                                    </a>

                                    <span class="header-cart-item-info">
                                        1 x $19.00
                                    </span>
                                </div>
                            </li>

                            <li class="header-cart-item">
                                <div class="header-cart-item-img">
                                    <img src="images/item-cart-02.jpg" alt="IMG">
                                </div>

                                <div class="header-cart-item-txt">
                                    <a href="#" class="header-cart-item-name">
                                        Converse All Star Hi Black Canvas
                                    </a>

                                    <span class="header-cart-item-info">
                                        1 x $39.00
                                    </span>
                                </div>
                            </li>

                            <li class="header-cart-item">
                                <div class="header-cart-item-img">
                                    <img src="images/item-cart-03.jpg" alt="IMG">
                                </div>

                                <div class="header-cart-item-txt">
                                    <a href="#" class="header-cart-item-name">
                                        Nixon Porter Leather Watch In Tan
                                    </a>

                                    <span class="header-cart-item-info">
                                        1 x $17.00
                                    </span>
                                </div>
                            </li>
                        </ul>

                        <div class="header-cart-total">
                            Total: $75.00
                        </div>

                        <div class="header-cart-buttons">
                            <div class="header-cart-wrapbtn">
                                <!-- Button -->
                                <a href="cart.html" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
                                    View Cart
                                </a>
                            </div>

                            <div class="header-cart-wrapbtn">
                                <!-- Button -->
                                <a href="#" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
                                    Check Out
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="btn-show-menu-mobile hamburger hamburger--squeeze">
                <span class="hamburger-box">
                    <span class="hamburger-inner"></span>
                </span>
            </div>
        </div>
    </div>

    <!-- Menu Mobile -->
    <div class="wrap-side-menu">
        <nav class="side-menu">
            <ul class="main-menu">
                <li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
                    <span class="topbar-child1">
                        Free shipping for standard order over $100
                    </span>
                </li>

                <li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
                    <div class="topbar-child2-mobile">
                        <span class="topbar-email">
                            fashe@example.com
                        </span>

                        <div class="topbar-language rs1-select2">
                            <select class="selection-1" name="time">
                                <option>USD</option>
                                <option>EUR</option>
                            </select>
                        </div>
                    </div>
                </li>

                <li class="item-topbar-mobile p-l-10">
                    <div class="topbar-social-mobile">
                        <a href="#" class="topbar-social-item fa fa-facebook"></a>
                        <a href="#" class="topbar-social-item fa fa-instagram"></a>
                        <a href="#" class="topbar-social-item fa fa-pinterest-p"></a>
                        <a href="#" class="topbar-social-item fa fa-snapchat-ghost"></a>
                        <a href="#" class="topbar-social-item fa fa-youtube-play"></a>
                    </div>
                </li>

                <li class="item-menu-mobile">
                    <a href="index.html">Home</a>
                    <ul class="sub-menu">
                        <li><a href="index.html">Homepage V1</a></li>
                        <li><a href="home-02.html">Homepage V2</a></li>
                        <li><a href="home-03.html">Homepage V3</a></li>
                    </ul>
                    <i class="arrow-main-menu fa fa-angle-right" aria-hidden="true"></i>
                </li>

                <li class="item-menu-mobile">
                    <a href="product.html">Shop</a>
                </li>

                <li class="item-menu-mobile">
                    <a href="product.html">Sale</a>
                </li>

                <li class="item-menu-mobile">
                    <a href="cart.html">Features</a>
                </li>

                <li class="item-menu-mobile">
                    <a href="about.html">About</a>
                </li>

                <li class="item-menu-mobile">
                    <a href="contact.html">Contact</a>
                </li>
            </ul>
        </nav>
    </div>
</header>